repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: black
        name: black
        entry: uv run black
        language: system
        types: [python]
        files: ^src/.*\.py$
        exclude: ^tests/.*$

      - id: isort
        name: isort
        entry: uv run isort
        language: system
        types: [python]
        files: ^src/.*\.py$
        exclude: ^tests/.*$

      - id: ruff
        name: ruff
        entry: uv run ruff check
        language: system
        types: [python]
        files: ^src/.*\.py$
        exclude: ^tests/.*$

      - id: mypy
        name: mypy
        entry: echo "Skipping mypy check for now"
        language: system
        types: [python]
        files: ^src/.*\.py$
        always_run: true
        pass_filenames: false
